/**
 * Common-Sense & Domain-Independent Seed Knowledge for AETHERIS.
 *
 * Provides a minimal, principled set of foundational concepts and relationships across:
 * 1. Physical Objects & Properties (Kettle, Apple, Water, Heat, Space)
 * 2. Computing Concepts (Python, Program, Database, Instructions)
 * 3. Temporal Principles (Past, Present, Future, Deadline, Completion)
 * 4. Quantitative & Economic Principles (Revenue, Cost, Margin, Quantity, Requirement)
 * 5. Epistemic & Causal Principles (Correlation, Causation, Hypothesis, Evidence, Uncertainty)
 */

import { Concept, Relationship, EvidenceLedger } from '../types/knowledge';

export function createEmptyEvidenceLedger(initialReliability = 1.0): EvidenceLedger {
  return {
    supportingCount: 1,
    contradictingCount: 0,
    successfulPredictions: 0,
    failedPredictions: 0,
    sourceReliability: initialReliability,
    history: [
      {
        id: `ev_init_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
        type: 'SUPPORTING',
        source: 'SYSTEM_SEED',
        description: 'Foundational common-sense ontology seed.',
        timestamp: new Date().toISOString(),
      },
    ],
  };
}

export function getCommonSenseSeedKnowledge(): { concepts: Concept[]; relationships: Relationship[] } {
  const now = new Date().toISOString();

  const concepts: Concept[] = [
    // -------------------------------------------------------------
    // Physical Objects & Materials
    // -------------------------------------------------------------
    {
      id: 'concept_physical_object',
      name: 'Physical Object',
      category: 'ONTOLOGY',
      description: 'An entity that has physical existence, occupies space, and has mass.',
      properties: {
        occupies_space: {
          key: 'occupies_space',
          value: true,
          confidence: 1.0,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_water',
      name: 'Water',
      category: 'MATERIAL',
      description: 'A clear, colorless liquid essential for life, boiling at high temperatures.',
      properties: {
        state_of_matter: {
          key: 'state_of_matter',
          value: 'liquid',
          confidence: 1.0,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_kettle',
      name: 'Kettle',
      category: 'APPLIANCE',
      description: 'A vessel or electric appliance designed for boiling or heating water.',
      properties: {
        is_appliance: {
          key: 'is_appliance',
          value: true,
          confidence: 0.95,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.95,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_apple',
      name: 'Apple',
      category: 'FRUIT',
      description: 'The round fruit of a tree of the rose family, typically green or red.',
      properties: {
        is_edible: {
          key: 'is_edible',
          value: true,
          confidence: 1.0,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_heat',
      name: 'Heat',
      category: 'PHYSICS',
      description: 'Thermal energy transferred between systems.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_fragile_object',
      name: 'Fragile Object',
      category: 'ONTOLOGY',
      description: 'An object easily broken or damaged when subject to impact.',
      properties: {
        fragile: {
          key: 'fragile',
          value: true,
          confidence: 0.95,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.95,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // -------------------------------------------------------------
    // Computing & Logic Concepts
    // -------------------------------------------------------------
    {
      id: 'concept_python',
      name: 'Python',
      category: 'LANGUAGE',
      description: 'A high-level, general-purpose programming language.',
      properties: {
        interpreted: {
          key: 'interpreted',
          value: true,
          confidence: 0.99,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.99,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_programming_language',
      name: 'Programming Language',
      category: 'COMPUTING',
      description: 'A formal language comprising a set of instructions that produce various kinds of output.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_program',
      name: 'Program',
      category: 'COMPUTING',
      description: 'A collection of instructions that can be executed by a computer.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_database',
      name: 'Database',
      category: 'COMPUTING',
      description: 'An organized collection of data stored and accessed electronically.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // -------------------------------------------------------------
    // Temporal Principles & Concepts
    // -------------------------------------------------------------
    {
      id: 'concept_past',
      name: 'Past',
      category: 'TEMPORAL',
      description: 'The time before the present moment; events that have already occurred.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_present',
      name: 'Present',
      category: 'TEMPORAL',
      description: 'The current moment in time.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_future',
      name: 'Future',
      category: 'TEMPORAL',
      description: 'The time after the present moment; events not yet observed.',
      properties: {
        is_observed: {
          key: 'is_observed',
          value: false,
          confidence: 1.0,
          source: 'SYSTEM_SEED',
          status: 'SEEDED',
          evidence: createEmptyEvidenceLedger(),
          lastUpdated: now,
        },
      },
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_deadline',
      name: 'Deadline',
      category: 'TEMPORAL',
      description: 'A specified latest time or date by which something should be completed.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // -------------------------------------------------------------
    // Quantitative & Economic Concepts
    // -------------------------------------------------------------
    {
      id: 'concept_revenue',
      name: 'Revenue',
      category: 'FINANCIAL',
      description: 'Total amount of income generated by the sale of goods or services.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_cost',
      name: 'Cost',
      category: 'FINANCIAL',
      description: 'An amount that must be paid or spent to buy or obtain something.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_margin',
      name: 'Margin',
      category: 'FINANCIAL',
      description: 'The difference between the revenue and the cost of production or transaction.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // -------------------------------------------------------------
    // Epistemic & Causal Concepts
    // -------------------------------------------------------------
    {
      id: 'concept_correlation',
      name: 'Correlation',
      category: 'EPISTEMIC',
      description: 'A statistical association between variables.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'concept_causation',
      name: 'Causation',
      category: 'EPISTEMIC',
      description: 'The relationship between cause and effect.',
      properties: {},
      relationshipIds: [],
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
  ];

  const relationships: Relationship[] = [
    // Physical Objects
    {
      id: 'rel_kettle_appliance',
      sourceConceptId: 'concept_kettle',
      predicate: 'IS_A',
      targetConceptId: 'concept_physical_object',
      targetDescription: 'Physical Object',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_kettle_heat_water',
      sourceConceptId: 'concept_kettle',
      predicate: 'USED_FOR',
      targetConceptId: 'concept_water',
      targetDescription: 'heating water',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.95,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_apple_fruit',
      sourceConceptId: 'concept_apple',
      predicate: 'IS_A',
      targetConceptId: 'concept_physical_object',
      targetDescription: 'Physical Object',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_heat_state_change',
      sourceConceptId: 'concept_heat',
      predicate: 'CAUSES',
      targetConceptId: 'concept_water',
      targetDescription: 'temperature increase and phase change',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.99,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_fragile_damage',
      sourceConceptId: 'concept_fragile_object',
      predicate: 'CAN',
      targetConceptId: 'concept_physical_object',
      targetDescription: 'be damaged by impact',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.95,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // Computing
    {
      id: 'rel_python_lang',
      sourceConceptId: 'concept_python',
      predicate: 'IS_A',
      targetConceptId: 'concept_programming_language',
      targetDescription: 'Programming Language',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_program_instructions',
      sourceConceptId: 'concept_program',
      predicate: 'REQUIRES',
      targetConceptId: 'concept_programming_language',
      targetDescription: 'instructions',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 0.99,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_database_stores_data',
      sourceConceptId: 'concept_database',
      predicate: 'USED_FOR',
      targetConceptId: 'concept_program',
      targetDescription: 'storing and querying data',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // Temporal
    {
      id: 'rel_past_before_present',
      sourceConceptId: 'concept_past',
      predicate: 'BEFORE',
      targetConceptId: 'concept_present',
      targetDescription: 'Present',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel_present_before_future',
      sourceConceptId: 'concept_present',
      predicate: 'BEFORE',
      targetConceptId: 'concept_future',
      targetDescription: 'Future',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },

    // Epistemic
    {
      id: 'rel_correlation_not_causation',
      sourceConceptId: 'concept_correlation',
      predicate: 'CANNOT',
      targetConceptId: 'concept_causation',
      targetDescription: 'automatically establish causation',
      source: 'SYSTEM_SEED',
      status: 'SEEDED',
      confidence: 1.0,
      evidence: createEmptyEvidenceLedger(),
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Link relationship IDs back to concepts
  for (const rel of relationships) {
    const concept = concepts.find((c) => c.id === rel.sourceConceptId);
    if (concept && !concept.relationshipIds.includes(rel.id)) {
      concept.relationshipIds.push(rel.id);
    }
  }

  return { concepts, relationships };
}
